language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"

matrix:
  include:
    - python: "3.5"
      env: TOXENV="py35-dj20"
    - python: "3.5"
      env: TOXENV="py35-dj21"
    - python: "3.5"
      env: TOXENV="py35-dj22"
    - python: "3.6"
      env: TOXENV="py36-dj20"
    - python: "3.6"
      env: TOXENV="py36-dj21"
    - python: "3.6"
      env: TOXENV="py36-dj22"
    - python: "3.7"
      env: TOXENV="py37-dj20"
    - python: "3.7"
      env: TOXENV="py37-dj21"
    - python: "3.7"
      env: TOXENV="py37-dj22"

install:
  - pip install tox

script:
  - tox

after_success:
  - coveralls
